# Euler problem 45
##########################
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#It can be verified that T285 = P165 = H143 = 40755.
#Find the next triangle number that is also pentagonal and hexagonal.

import time
start = time.time()

#function to check if the given number is pentagonal
def is_pentagonal(p):
    if (1+(24*p+1)**0.5) % 6 == 0:
        return True
    return False

#function to check if the given number is hexagonal
def is_hexagonal(h):
    if (1+(8*h+1)**0.5) % 4 == 0:
        return True
    return False

# iterator start after 285
i = 286

# while loop for iterating
while True:
    triangle = i*(i+1)/2
    if is_pentagonal(triangle) and is_hexagonal(triangle):
        print triangle
        break
    i += 1

print("This took " + str(time.time() - start) + " seconds")
